name: MyATS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  - name: Install Dependencies

  install-root:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with: 
          node-version: '20'
      - run: npm install

  build-frontend:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with: 
          node-version: '20'
      - run: npm run "ci-frontend"

  build-backend:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with: 
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: npm run "setup-backend"
